### ISSUE TITLE
remove flannel.${VNI} interfaces when cleaning up Flannel network state

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/flannel-operator#19]
We have the following state still left over. As of now it does not seem to hurt us, but to properly cleanup the hosts we should make sure the interfaces associated to a guest cluster are removed as soon as the guest cluster is deleted. 

```
xh3b4sd@0000dd1bb02a188c ~ $ networkctl | grep flannel
236 flannel.4        ether              routable    configured
248 flannel.5        ether              routable    configured
251 flannel.6        ether              routable    configured
254 flannel.7        ether              routable    configured
257 flannel.8        ether              routable    configuring
260 flannel.9        ether              routable    configuring
264 flannel.10       ether              routable    configuring
267 flannel.11       ether              routable    configuring
270 flannel.12       ether              routable    configuring
273 flannel.13       ether              routable    configuring
278 flannel.14       ether              routable    configuring
```

See https://unix.stackexchange.com/a/324535/183918.

**Comment by xh3b4sd** [comment]
IMO this is done. Lycan and centaur are safe. Don't know about anubis. The implementation is fixed and as soon as the "stuck in terminating" bug is fixed on the host cluster this is not a problem anymore. Closing this now.

**Comment by calvix** [comment]
all envs were cleaned of network trash
