### ISSUE TITLE
properly reconcile flannel resources

### ISSUE THREAD

**Issue by calvix** [giantswarm/flannel-operator#56]
Flannel should health check if the bridge that is created exists and if it has assigned ip.

It should also check if the flannel device exists.

If not it should restart

**Comment by xh3b4sd** [comment]
This is part of the migration to the reconciler framework. The operator has to properly reconcile, which it does not yet.

**Comment by calvix** [comment]
No, i don't care about operator reconciling. This is a different story.

There has to be check in the `flannel-network` pod that will assure that there is always assigned ip for the bridge. If that is not fulfilled pod should be restarted/killed. k8s will do it for us.

flannel-network-pod can run for several days and for some reason sometimes when a pod is deleted and recreated on the same machine the bridge doesn't have ip and it broke the whole VM.

when this happens on 8 machines it's super frustrating

**Comment by calvix** [comment]
We need same healtcheck we do in `k8s-kvm`
```
while :; do
  NETWORK_BRIDGE_IP=$(/sbin/ifconfig ${NETWORK_BRIDGE_NAME} | grep 'inet ' | awk '{print $2}' | cut -d ':' -f 2)
  if [ ! -z "${NETWORK_BRIDGE_IP}" ]; then
    break
  fi
  echo "Waiting for ip address on interface ${NETWORK_BRIDGE_IP}."
  sleep 1
done
```

**Comment by xh3b4sd** [comment]
Where do we need this health check? Who should do it? When should this be done? Is it that flanneld is running and for some reason the bridge does not have a IP anymore? Or is it that the bridge is gone for some reason after a while? There is a healthcheck in flanneld. See https://github.com/coreos/flannel/blob/f5542377cf8e70d52d50cb3353ad756c20cb7324/Documentation/configuration.md#health-check. Would it help to configure this?

**Comment by calvix** [comment]
Flanneld is not creating the bridge, its `systemd-networkd` service.

This health check should be part of `flannel-network-xxx` pod, it should be health check by k8s and if it's not healthy pod `k8s-network-bridge` should be restarted.

**Comment by xh3b4sd** [comment]
Ok cool. Then feel free to just take this. You know shit. <3

**Comment by calvix** [comment]
done works as expected
